* Odump

Introduction goes here

* Dependencies

  The dependencies can be found in the following debian packages.

  - libbatteries-ocaml-dev
  - libconfig-file-ocaml-dev
  - libcryptokit-ocaml-dev
  - libfindlib-ocaml-dev
  - libocamlnet-ocaml-dev
  - libounit-ocaml-dev
  - libpxp-ocaml-dev
  - libsqlite3-ocaml-dev
  - libuuidm-ocaml-dev
  - libzip-ocaml-dev
  - ocaml-findlib

  This can be installed easily with something like:

  sudo apt-get install ocaml-findlib libbatteries-ocaml-dev \
       libcryptokit-ocaml-dev libounit-ocaml-dev libpxp-ocaml-dev \
       libuuidm-ocaml-dev libzip-ocaml-dev libfindlib-ocaml-dev \
       libsqlite3-ocaml-dev

On Arch, the following seems sufficient to build (many are AUR):

  - ocaml
  - ocaml-findlib
  - ocaml-batteries (pulls in ocaml-camomile, ocaml-ounit)
  - ocaml-zip
  - ocaml-cryptokit
  - ocamlnet (pulls in ocaml-pcre, ocaml-ssl)
  - ocaml-pxp
  - ocaml-sqlite3

On Fedora:

  - Just install ocaml, and use Opam below)
  - Will need:
    libattr-devel

Unfortunately, several libraries pull in camomile, which has a
dependency on a fairly large runtime library.  TODO: Figure out how to
point directly at this library so that this can be used on a rescue
image.

* Opam

  Things are easier to install with opam.

  - install opam

  - opam init
    follow the instructions

  - opam install ocamlfind

  - opam install ounit ocamlnet pxp sqlite3-ocaml camlzip batteries \
       cryptokit

    (note that in some instances, opam will build things multiple
    times if you do the install steps separately)
